# https://faun.pub/building-a-ci-cd-pipeline-with-github-actions-and-docker-part-1-a9d8709c31fb
name: CI-dev-pipeline
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ] # to change to develop
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      # As we would be utilising docker commands to spin up the containers, we need to run the environment using an
      # image lucasalt/act_base created by LucasCtrl. Without this, we will not be able to run docker-compose which
      # is required to spin up the containers.
      image: lucasalt/act_base:latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: "neighborhood_bazar"
      - name: RunOne
        run: |
	      echo Hello, world!
